apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: opforcements-admin
type: Opaque
stringData:
  POSTGRES_DB: opforcements
  POSTGRES_USER: opf
  POSTGRES_PASSWORD: "opf-admin-db-2024"
