apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: opforcements-apex
type: Opaque
stringData:
  DATABASE_URL: "postgresql://opf:opf-apex-db-2024@postgres:5432/opforcements"
  JWT_SECRET: "apex-jwt-secret-change-in-prod-2024"
