from datetime import date
from .auth import hash_password

TENANT_NAME = "Meridian Financial Group"

USERS = [
    {"id": "U001", "name": "Sarah Chen", "email": "admin@meridian-fg.com",
     "title": "Director of Sales Engineering", "specialty": "Security",
     "slack_handle": "schen", "role": "admin",
     "password_hash": hash_password("Meridian123!")},
    {"id": "U002", "name": "James Porter", "email": "j.porter@meridian-fg.com",
     "title": "Network Solutions Architect", "specialty": "Networking",
     "slack_handle": "jporter", "role": "user",
     "password_hash": hash_password("Meridian123!")},
    {"id": "U003", "name": "Michelle Davis", "email": "m.davis@meridian-fg.com",
     "title": "Compliance & Security Engineer", "specialty": "Security",
     "slack_handle": "mdavis", "role": "user",
     "password_hash": hash_password("Meridian123!")},
    {"id": "U004", "name": "Robert Kim", "email": "r.kim@meridian-fg.com",
     "title": "Cloud Infrastructure Lead", "specialty": "Cloud Infrastructure",
     "slack_handle": "rkim", "role": "user",
     "password_hash": hash_password("Meridian123!")},
    {"id": "U005", "name": "Lisa Thompson", "email": "l.thompson@meridian-fg.com",
     "title": "AI/ML Solutions Engineer", "specialty": "AI/ML",
     "slack_handle": "lthompson", "role": "user",
     "password_hash": hash_password("Meridian123!")},
    {"id": "U006", "name": "Daniel Park", "email": "d.park@meridian-fg.com",
     "title": "Storage & Data Engineer", "specialty": "Storage",
     "slack_handle": "dpark", "role": "user",
     "password_hash": hash_password("Meridian123!")},
]

ACCOUNTS = [
    # New York
    {"id": "A001", "name": "Manhattan Capital Bank", "billing_city": "New York",
     "billing_state": "NY", "industry": "Banking", "annual_revenue": 4_200_000_000,
     "account_type": "Customer", "product_interest": "Security", "owner_id": "U003"},
    {"id": "A002", "name": "Apex Trading Systems", "billing_city": "New York",
     "billing_state": "NY", "industry": "Financial Trading", "annual_revenue": 890_000_000,
     "account_type": "Customer", "product_interest": "Networking", "owner_id": "U002"},
    {"id": "A003", "name": "Summit Risk Analytics", "billing_city": "New York",
     "billing_state": "NY", "industry": "Risk Management", "annual_revenue": 560_000_000,
     "account_type": "Prospect", "product_interest": "AI/ML", "owner_id": "U005"},
    {"id": "A004", "name": "Gotham Asset Management", "billing_city": "New York",
     "billing_state": "NY", "industry": "Asset Management", "annual_revenue": 7_800_000_000,
     "account_type": "Prospect", "product_interest": "Cloud Infrastructure", "owner_id": "U004"},
    # Boston
    {"id": "A005", "name": "Liberty Insurance Corp", "billing_city": "Boston",
     "billing_state": "MA", "industry": "Insurance", "annual_revenue": 3_100_000_000,
     "account_type": "Prospect", "product_interest": "Cloud Infrastructure", "owner_id": "U004"},
    {"id": "A006", "name": "Harbor Wealth Partners", "billing_city": "Boston",
     "billing_state": "MA", "industry": "Wealth Management", "annual_revenue": 1_200_000_000,
     "account_type": "Customer", "product_interest": "AI/ML", "owner_id": "U005"},
    # Chicago
    {"id": "A007", "name": "NorthStar Wealth Management", "billing_city": "Chicago",
     "billing_state": "IL", "industry": "Wealth Management", "annual_revenue": 720_000_000,
     "account_type": "Prospect", "product_interest": "AI/ML", "owner_id": "U005"},
    {"id": "A008", "name": "Lakefront Credit Union", "billing_city": "Chicago",
     "billing_state": "IL", "industry": "Banking", "annual_revenue": 480_000_000,
     "account_type": "Customer", "product_interest": "Security", "owner_id": "U001"},
    # Dallas / Houston
    {"id": "A009", "name": "Cornerstone Payment Systems", "billing_city": "Dallas",
     "billing_state": "TX", "industry": "Payment Processing", "annual_revenue": 1_100_000_000,
     "account_type": "Customer", "product_interest": "Security", "owner_id": "U003"},
    {"id": "A010", "name": "Lone Star Capital Group", "billing_city": "Houston",
     "billing_state": "TX", "industry": "Private Equity", "annual_revenue": 2_400_000_000,
     "account_type": "Prospect", "product_interest": "Kubernetes Platform", "owner_id": "U001"},
    # San Francisco
    {"id": "A011", "name": "Pacific Exchange Group", "billing_city": "San Francisco",
     "billing_state": "CA", "industry": "Securities Exchange", "annual_revenue": 1_800_000_000,
     "account_type": "Customer", "product_interest": "Kubernetes Platform", "owner_id": "U001"},
    {"id": "A012", "name": "Bay Area Clearing House", "billing_city": "San Francisco",
     "billing_state": "CA", "industry": "Financial Clearing", "annual_revenue": 640_000_000,
     "account_type": "Prospect", "product_interest": "Networking", "owner_id": "U002"},
    # Miami
    {"id": "A013", "name": "Atlantic Fintech Partners", "billing_city": "Miami",
     "billing_state": "FL", "industry": "FinTech", "annual_revenue": 340_000_000,
     "account_type": "Prospect", "product_interest": "Networking", "owner_id": "U002"},
    {"id": "A014", "name": "Sunshine State Credit", "billing_city": "Miami",
     "billing_state": "FL", "industry": "Consumer Finance", "annual_revenue": 890_000_000,
     "account_type": "Customer", "product_interest": "Storage", "owner_id": "U006"},
    # Washington DC
    {"id": "A015", "name": "Federal Bancorp Solutions", "billing_city": "Washington",
     "billing_state": "DC", "industry": "Government Banking", "annual_revenue": 5_600_000_000,
     "account_type": "Prospect", "product_interest": "Security", "owner_id": "U003"},
    # Philadelphia
    {"id": "A016", "name": "Keystone Financial Services", "billing_city": "Philadelphia",
     "billing_state": "PA", "industry": "Financial Services", "annual_revenue": 1_700_000_000,
     "account_type": "Customer", "product_interest": "Cloud Infrastructure", "owner_id": "U004"},
]

CONTACTS = [
    {"id": "C001", "account_id": "A001", "first_name": "William", "last_name": "Hartley",
     "title": "CISO", "email": "w.hartley@manhattancapital.com", "is_executive": 1},
    {"id": "C002", "account_id": "A001", "first_name": "Irene", "last_name": "Zhou",
     "title": "VP Security Operations", "email": "i.zhou@manhattancapital.com", "is_executive": 0},
    {"id": "C003", "account_id": "A002", "first_name": "Victoria", "last_name": "Zhao",
     "title": "CTO", "email": "v.zhao@apextrading.com", "is_executive": 1},
    {"id": "C004", "account_id": "A002", "first_name": "Patrick", "last_name": "Duffy",
     "title": "Head of Network Infrastructure", "email": "p.duffy@apextrading.com", "is_executive": 0},
    {"id": "C005", "account_id": "A003", "first_name": "Natasha", "last_name": "Romero",
     "title": "Chief Risk Officer", "email": "n.romero@summitrisK.com", "is_executive": 1},
    {"id": "C006", "account_id": "A004", "first_name": "Charles", "last_name": "Whitmore",
     "title": "CTO", "email": "c.whitmore@gothamasset.com", "is_executive": 1},
    {"id": "C007", "account_id": "A004", "first_name": "Fiona", "last_name": "Blackwell",
     "title": "VP Cloud Strategy", "email": "f.blackwell@gothamasset.com", "is_executive": 1},
    {"id": "C008", "account_id": "A005", "first_name": "Thomas", "last_name": "Reeves",
     "title": "VP Technology", "email": "t.reeves@libertyins.com", "is_executive": 1},
    {"id": "C009", "account_id": "A005", "first_name": "Carol", "last_name": "Jennings",
     "title": "Cloud Architect", "email": "c.jennings@libertyins.com", "is_executive": 0},
    {"id": "C010", "account_id": "A006", "first_name": "Henry", "last_name": "Donovan",
     "title": "CIO", "email": "h.donovan@harborwealth.com", "is_executive": 1},
    {"id": "C011", "account_id": "A007", "first_name": "Olivia", "last_name": "Grant",
     "title": "Head of Technology", "email": "o.grant@northstarwealth.com", "is_executive": 1},
    {"id": "C012", "account_id": "A008", "first_name": "Derek", "last_name": "Okafor",
     "title": "CISO", "email": "d.okafor@lakefrontcu.com", "is_executive": 1},
    {"id": "C013", "account_id": "A009", "first_name": "Kevin", "last_name": "Walsh",
     "title": "CTO", "email": "k.walsh@cornerstonepay.com", "is_executive": 1},
    {"id": "C014", "account_id": "A009", "first_name": "Monica", "last_name": "Espinoza",
     "title": "Director of Security Compliance", "email": "m.espinoza@cornerstonepay.com", "is_executive": 0},
    {"id": "C015", "account_id": "A010", "first_name": "Brett", "last_name": "Caldwell",
     "title": "VP Technology", "email": "b.caldwell@lonestar.com", "is_executive": 1},
    {"id": "C016", "account_id": "A011", "first_name": "Angela", "last_name": "Morrison",
     "title": "Head of Engineering", "email": "a.morrison@pacificexchange.com", "is_executive": 1},
    {"id": "C017", "account_id": "A011", "first_name": "Ian", "last_name": "Fletcher",
     "title": "Platform Engineering Lead", "email": "i.fletcher@pacificexchange.com", "is_executive": 0},
    {"id": "C018", "account_id": "A012", "first_name": "Sandra", "last_name": "Nguyen",
     "title": "CTO", "email": "s.nguyen@bayareaclearing.com", "is_executive": 1},
    {"id": "C019", "account_id": "A013", "first_name": "Rafael", "last_name": "Cruz",
     "title": "CTO", "email": "r.cruz@atlanticfintech.com", "is_executive": 1},
    {"id": "C020", "account_id": "A014", "first_name": "Bianca", "last_name": "Torres",
     "title": "VP IT Infrastructure", "email": "b.torres@sunshinecredit.com", "is_executive": 1},
    {"id": "C021", "account_id": "A015", "first_name": "Raymond", "last_name": "Clarke",
     "title": "CISO", "email": "r.clarke@federalbancorp.gov", "is_executive": 1},
    {"id": "C022", "account_id": "A016", "first_name": "Helen", "last_name": "Marsh",
     "title": "CIO", "email": "h.marsh@keystonefinancial.com", "is_executive": 1},
    {"id": "C023", "account_id": "A016", "first_name": "Tom", "last_name": "Byrne",
     "title": "Head of Cloud Infrastructure", "email": "t.byrne@keystonefinancial.com", "is_executive": 0},
]

OPPORTUNITIES = [
    # New York
    {"id": "O001", "account_id": "A001", "owner_id": "U003",
     "name": "Manhattan Capital - SOC2 Compliance Platform", "amount": 2_800_000,
     "probability": 80, "stage": "Negotiation/Review", "close_date": date(2026, 6, 30)},
    {"id": "O002", "account_id": "A001", "owner_id": "U003",
     "name": "Manhattan Capital - Insider Threat Detection", "amount": 950_000,
     "probability": 70, "stage": "Proposal/Price Quote", "close_date": date(2026, 8, 15)},
    {"id": "O003", "account_id": "A002", "owner_id": "U002",
     "name": "Apex Trading - Ultra-Low Latency Network Upgrade", "amount": 1_900_000,
     "probability": 75, "stage": "Proposal/Price Quote", "close_date": date(2026, 7, 31)},
    {"id": "O004", "account_id": "A002", "owner_id": "U002",
     "name": "Apex Trading - Network Observability Suite", "amount": 480_000,
     "probability": 80, "stage": "Negotiation/Review", "close_date": date(2026, 6, 20)},
    {"id": "O005", "account_id": "A003", "owner_id": "U005",
     "name": "Summit Risk - ML Fraud Detection Engine", "amount": 740_000,
     "probability": 65, "stage": "Value Proposition", "close_date": date(2026, 8, 31)},
    {"id": "O006", "account_id": "A004", "owner_id": "U004",
     "name": "Gotham Asset - Hybrid Cloud Migration", "amount": 3_600_000,
     "probability": 45, "stage": "Needs Analysis", "close_date": date(2026, 10, 31)},
    # Boston
    {"id": "O007", "account_id": "A005", "owner_id": "U004",
     "name": "Liberty Insurance - Hybrid Cloud Migration", "amount": 2_200_000,
     "probability": 55, "stage": "Needs Analysis", "close_date": date(2026, 10, 31)},
    {"id": "O008", "account_id": "A005", "owner_id": "U003",
     "name": "Liberty Insurance - Data Loss Prevention", "amount": 680_000,
     "probability": 50, "stage": "Qualification", "close_date": date(2026, 11, 30)},
    {"id": "O009", "account_id": "A006", "owner_id": "U005",
     "name": "Harbor Wealth - AI Portfolio Advisor", "amount": 1_150_000,
     "probability": 70, "stage": "Proposal/Price Quote", "close_date": date(2026, 8, 15)},
    # Chicago
    {"id": "O010", "account_id": "A007", "owner_id": "U005",
     "name": "NorthStar - AI Portfolio Risk Engine", "amount": 980_000,
     "probability": 60, "stage": "Value Proposition", "close_date": date(2026, 9, 30)},
    {"id": "O011", "account_id": "A008", "owner_id": "U001",
     "name": "Lakefront CU - FFIEC Compliance Platform", "amount": 620_000,
     "probability": 75, "stage": "Proposal/Price Quote", "close_date": date(2026, 7, 31)},
    {"id": "O012", "account_id": "A008", "owner_id": "U003",
     "name": "Lakefront CU - Endpoint Security Suite", "amount": 210_000,
     "probability": 85, "stage": "Negotiation/Review", "close_date": date(2026, 6, 15)},
    # Dallas / Houston
    {"id": "O013", "account_id": "A009", "owner_id": "U003",
     "name": "Cornerstone Pay - PCI-DSS Security Stack", "amount": 1_650_000,
     "probability": 85, "stage": "Negotiation/Review", "close_date": date(2026, 6, 15)},
    {"id": "O014", "account_id": "A009", "owner_id": "U006",
     "name": "Cornerstone Pay - Transaction Audit Storage", "amount": 540_000,
     "probability": 80, "stage": "Proposal/Price Quote", "close_date": date(2026, 7, 15)},
    {"id": "O015", "account_id": "A010", "owner_id": "U001",
     "name": "Lone Star Capital - K8s Trading Platform", "amount": 2_100_000,
     "probability": 40, "stage": "Qualification", "close_date": date(2026, 12, 31)},
    # San Francisco
    {"id": "O016", "account_id": "A011", "owner_id": "U001",
     "name": "Pacific Exchange - K8s Trading Platform", "amount": 3_400_000,
     "probability": 70, "stage": "Proposal/Price Quote", "close_date": date(2026, 8, 15)},
    {"id": "O017", "account_id": "A012", "owner_id": "U002",
     "name": "Bay Area Clearing - Network Infrastructure", "amount": 870_000,
     "probability": 50, "stage": "Needs Analysis", "close_date": date(2026, 10, 15)},
    # Miami
    {"id": "O018", "account_id": "A013", "owner_id": "U002",
     "name": "Atlantic Fintech - SD-WAN Deployment", "amount": 490_000,
     "probability": 50, "stage": "Value Proposition", "close_date": date(2026, 11, 30)},
    {"id": "O019", "account_id": "A014", "owner_id": "U006",
     "name": "Sunshine State Credit - Archive Storage", "amount": 360_000,
     "probability": 65, "stage": "Proposal/Price Quote", "close_date": date(2026, 9, 30)},
    # DC
    {"id": "O020", "account_id": "A015", "owner_id": "U003",
     "name": "Federal Bancorp - FedRAMP Security Platform", "amount": 4_800_000,
     "probability": 35, "stage": "Qualification", "close_date": date(2026, 12, 31)},
    # Philadelphia
    {"id": "O021", "account_id": "A016", "owner_id": "U004",
     "name": "Keystone Financial - Cloud Infrastructure Refresh", "amount": 1_900_000,
     "probability": 60, "stage": "Value Proposition", "close_date": date(2026, 9, 30)},
    {"id": "O022", "account_id": "A016", "owner_id": "U006",
     "name": "Keystone Financial - Disaster Recovery Platform", "amount": 520_000,
     "probability": 55, "stage": "Needs Analysis", "close_date": date(2026, 10, 31)},
    {"id": "O023", "account_id": "A007", "owner_id": "U005",
     "name": "NorthStar - Client Reporting Automation", "amount": 390_000,
     "probability": 45, "stage": "Qualification", "close_date": date(2026, 11, 30)},
    {"id": "O024", "account_id": "A004", "owner_id": "U005",
     "name": "Gotham Asset - Quant Model Infrastructure", "amount": 1_200_000,
     "probability": 35, "stage": "Prospecting", "close_date": date(2027, 2, 28)},
]

CONFERENCES = [
    {"id": "CF001", "name": "FinTech Summit NY 2026", "city": "New York", "state": "NY",
     "start_date": date(2026, 6, 9), "end_date": date(2026, 6, 11), "ebx_slots": 8,
     "description": "Premier fintech and banking technology conference"},
    {"id": "CF002", "name": "Money20/20 Vegas 2026", "city": "Las Vegas", "state": "NV",
     "start_date": date(2026, 10, 26), "end_date": date(2026, 10, 29), "ebx_slots": 10,
     "description": "Global fintech and payments event"},
    {"id": "CF003", "name": "Sibos 2026", "city": "Toronto", "state": "ON",
     "start_date": date(2026, 10, 12), "end_date": date(2026, 10, 15), "ebx_slots": 6,
     "description": "SWIFT global banking operations conference"},
]

ATTENDEES = [
    # FinTech Summit NY
    {"conf_id": "CF001", "user_id": "U001", "role": "Sales Lead",
     "hotel": "Marriott Marquis Times Square", "hotel_addr": "1535 Broadway, New York, NY 10036",
     "check_in": date(2026, 6, 8), "check_out": date(2026, 6, 12),
     "flight_in": "DL 301 · Jun 8 · JFK arrives 3:00 PM",
     "flight_out": "DL 304 · Jun 12 · Departs JFK 6:00 PM"},
    {"conf_id": "CF001", "user_id": "U003", "role": "Security Lead",
     "hotel": "Marriott Marquis Times Square", "hotel_addr": "1535 Broadway, New York, NY 10036",
     "check_in": date(2026, 6, 9), "check_out": date(2026, 6, 11),
     "flight_in": "AA 712 · Jun 9 · JFK arrives 10:00 AM",
     "flight_out": "AA 715 · Jun 11 · Departs JFK 7:30 PM"},
    {"conf_id": "CF001", "user_id": "U005", "role": "AI/ML Solutions Lead",
     "hotel": "Hilton Midtown", "hotel_addr": "1335 6th Ave, New York, NY 10019",
     "check_in": date(2026, 6, 9), "check_out": date(2026, 6, 11),
     "flight_in": "UA 201 · Jun 9 · EWR arrives 9:00 AM",
     "flight_out": "UA 204 · Jun 11 · Departs EWR 8:00 PM"},
    # Money20/20 Las Vegas
    {"conf_id": "CF002", "user_id": "U001", "role": "Sales Lead",
     "hotel": "The Venetian Resort", "hotel_addr": "3355 Las Vegas Blvd S, Las Vegas, NV 89109",
     "check_in": date(2026, 10, 25), "check_out": date(2026, 10, 30),
     "flight_in": "SW 445 · Oct 25 · LAS arrives 1:00 PM",
     "flight_out": "SW 448 · Oct 30 · Departs LAS 4:00 PM"},
    {"conf_id": "CF002", "user_id": "U002", "role": "Networking Lead",
     "hotel": "The Palazzo", "hotel_addr": "3325 Las Vegas Blvd S, Las Vegas, NV 89109",
     "check_in": date(2026, 10, 26), "check_out": date(2026, 10, 29),
     "flight_in": "UA 887 · Oct 26 · LAS arrives 9:00 AM",
     "flight_out": "UA 890 · Oct 29 · Departs LAS 7:00 PM"},
    {"conf_id": "CF002", "user_id": "U005", "role": "AI Demo Lead",
     "hotel": "The Venetian Resort", "hotel_addr": "3355 Las Vegas Blvd S, Las Vegas, NV 89109",
     "check_in": date(2026, 10, 26), "check_out": date(2026, 10, 29),
     "flight_in": "DL 512 · Oct 26 · LAS arrives 11:00 AM",
     "flight_out": "DL 515 · Oct 29 · Departs LAS 6:00 PM"},
    # Sibos Toronto
    {"conf_id": "CF003", "user_id": "U001", "role": "Sales Lead",
     "hotel": "Fairmont Royal York", "hotel_addr": "100 Front St W, Toronto, ON M5J 1E3",
     "check_in": date(2026, 10, 11), "check_out": date(2026, 10, 16),
     "flight_in": "AC 802 · Oct 11 · YYZ arrives 2:00 PM",
     "flight_out": "AC 805 · Oct 16 · Departs YYZ 5:00 PM"},
    {"conf_id": "CF003", "user_id": "U003", "role": "Compliance Lead",
     "hotel": "Fairmont Royal York", "hotel_addr": "100 Front St W, Toronto, ON M5J 1E3",
     "check_in": date(2026, 10, 12), "check_out": date(2026, 10, 15),
     "flight_in": "UA 441 · Oct 12 · YYZ arrives 10:00 AM",
     "flight_out": "UA 444 · Oct 15 · Departs YYZ 7:00 PM"},
]
