from datetime import date
from .auth import hash_password

TENANT_NAME = "NovaTech Systems"

USERS = [
    {"id": "U001", "name": "Marcus Rodriguez", "email": "admin@novatech.io",
     "title": "VP Sales Engineering", "specialty": "Kubernetes Platform",
     "slack_handle": "mrodriguez", "role": "admin",
     "password_hash": hash_password("NovaTech123!")},
    {"id": "U002", "name": "Jennifer Wu", "email": "j.wu@novatech.io",
     "title": "Cloud Architect", "specialty": "Cloud Infrastructure",
     "slack_handle": "jwu", "role": "user",
     "password_hash": hash_password("NovaTech123!")},
    {"id": "U003", "name": "Alex Kim", "email": "a.kim@novatech.io",
     "title": "AI/ML Solutions Engineer", "specialty": "AI/ML",
     "slack_handle": "akim", "role": "user",
     "password_hash": hash_password("NovaTech123!")},
    {"id": "U004", "name": "David Torres", "email": "d.torres@novatech.io",
     "title": "Security Architect", "specialty": "Security",
     "slack_handle": "dtorres", "role": "user",
     "password_hash": hash_password("NovaTech123!")},
    {"id": "U005", "name": "Rachel Chen", "email": "r.chen@novatech.io",
     "title": "Networking Specialist", "specialty": "Networking",
     "slack_handle": "rchen", "role": "user",
     "password_hash": hash_password("NovaTech123!")},
    {"id": "U006", "name": "Tyler Johnson", "email": "t.johnson@novatech.io",
     "title": "Storage Engineer", "specialty": "Storage",
     "slack_handle": "tjohnson", "role": "user",
     "password_hash": hash_password("NovaTech123!")},
]

ACCOUNTS = [
    # Bay Area
    {"id": "A001", "name": "Quantum Leap Technologies", "billing_city": "San Francisco",
     "billing_state": "CA", "industry": "Artificial Intelligence", "annual_revenue": 85_000_000,
     "account_type": "Customer", "product_interest": "AI/ML", "owner_id": "U003"},
    {"id": "A002", "name": "CloudSphere Inc", "billing_city": "San Jose",
     "billing_state": "CA", "industry": "Cloud Software", "annual_revenue": 210_000_000,
     "account_type": "Customer", "product_interest": "Kubernetes Platform", "owner_id": "U001"},
    {"id": "A003", "name": "DataVault Systems", "billing_city": "Palo Alto",
     "billing_state": "CA", "industry": "Data Management", "annual_revenue": 140_000_000,
     "account_type": "Prospect", "product_interest": "Storage", "owner_id": "U006"},
    {"id": "A004", "name": "SecureEdge Networks", "billing_city": "Mountain View",
     "billing_state": "CA", "industry": "Cybersecurity", "annual_revenue": 320_000_000,
     "account_type": "Customer", "product_interest": "Security", "owner_id": "U004"},
    {"id": "A005", "name": "HorizonScale", "billing_city": "San Francisco",
     "billing_state": "CA", "industry": "Infrastructure SaaS", "annual_revenue": 95_000_000,
     "account_type": "Prospect", "product_interest": "Cloud Infrastructure", "owner_id": "U002"},
    {"id": "A006", "name": "ByteStream Analytics", "billing_city": "Oakland",
     "billing_state": "CA", "industry": "Data Analytics", "annual_revenue": 67_000_000,
     "account_type": "Prospect", "product_interest": "AI/ML", "owner_id": "U003"},
    {"id": "A007", "name": "DevPipeline Co", "billing_city": "Sunnyvale",
     "billing_state": "CA", "industry": "DevOps Tooling", "annual_revenue": 180_000_000,
     "account_type": "Customer", "product_interest": "Kubernetes Platform", "owner_id": "U001"},
    {"id": "A008", "name": "NexGen Cloud", "billing_city": "Santa Clara",
     "billing_state": "CA", "industry": "Cloud Services", "annual_revenue": 450_000_000,
     "account_type": "Customer", "product_interest": "Cloud Infrastructure", "owner_id": "U002"},
    # Seattle
    {"id": "A009", "name": "PacketForge Networks", "billing_city": "Seattle",
     "billing_state": "WA", "industry": "Networking Software", "annual_revenue": 120_000_000,
     "account_type": "Prospect", "product_interest": "Networking", "owner_id": "U005"},
    {"id": "A010", "name": "CascadeAI Labs", "billing_city": "Seattle",
     "billing_state": "WA", "industry": "AI Research", "annual_revenue": 55_000_000,
     "account_type": "Prospect", "product_interest": "AI/ML", "owner_id": "U003"},
    {"id": "A011", "name": "StackNorth Engineering", "billing_city": "Bellevue",
     "billing_state": "WA", "industry": "Platform Engineering", "annual_revenue": 230_000_000,
     "account_type": "Customer", "product_interest": "Kubernetes Platform", "owner_id": "U001"},
    # Austin
    {"id": "A012", "name": "GridLock Security", "billing_city": "Austin",
     "billing_state": "TX", "industry": "Cybersecurity", "annual_revenue": 175_000_000,
     "account_type": "Customer", "product_interest": "Security", "owner_id": "U004"},
    {"id": "A013", "name": "LonghornData Systems", "billing_city": "Austin",
     "billing_state": "TX", "industry": "Data Analytics", "annual_revenue": 48_000_000,
     "account_type": "Prospect", "product_interest": "Storage", "owner_id": "U006"},
    # Denver
    {"id": "A014", "name": "AlpineCode Systems", "billing_city": "Denver",
     "billing_state": "CO", "industry": "Software Development", "annual_revenue": 92_000_000,
     "account_type": "Customer", "product_interest": "Cloud Infrastructure", "owner_id": "U002"},
    {"id": "A015", "name": "MeshPoint IoT", "billing_city": "Boulder",
     "billing_state": "CO", "industry": "IoT Platform", "annual_revenue": 38_000_000,
     "account_type": "Prospect", "product_interest": "Kubernetes Platform", "owner_id": "U001"},
    # New York
    {"id": "A016", "name": "EdgeSync Technologies", "billing_city": "New York",
     "billing_state": "NY", "industry": "Edge Computing", "annual_revenue": 310_000_000,
     "account_type": "Prospect", "product_interest": "Networking", "owner_id": "U005"},
]

CONTACTS = [
    {"id": "C001", "account_id": "A001", "first_name": "Priya", "last_name": "Patel",
     "title": "CTO", "email": "p.patel@quantumleap.io", "is_executive": 1},
    {"id": "C002", "account_id": "A001", "first_name": "Jordan", "last_name": "Osei",
     "title": "Head of MLOps", "email": "j.osei@quantumleap.io", "is_executive": 0},
    {"id": "C003", "account_id": "A002", "first_name": "Nathan", "last_name": "Brooks",
     "title": "VP Engineering", "email": "n.brooks@cloudsphere.com", "is_executive": 1},
    {"id": "C004", "account_id": "A002", "first_name": "Diana", "last_name": "Cheng",
     "title": "Platform Engineering Lead", "email": "d.cheng@cloudsphere.com", "is_executive": 0},
    {"id": "C005", "account_id": "A003", "first_name": "Matt", "last_name": "Hogan",
     "title": "VP Infrastructure", "email": "m.hogan@datavault.io", "is_executive": 1},
    {"id": "C006", "account_id": "A004", "first_name": "Zoe", "last_name": "Martinez",
     "title": "CISO", "email": "z.martinez@secureedge.com", "is_executive": 1},
    {"id": "C007", "account_id": "A004", "first_name": "Brian", "last_name": "Walsh",
     "title": "Director of Security Engineering", "email": "b.walsh@secureedge.com", "is_executive": 0},
    {"id": "C008", "account_id": "A005", "first_name": "Sasha", "last_name": "Novak",
     "title": "CTO", "email": "s.novak@horizonscale.io", "is_executive": 1},
    {"id": "C009", "account_id": "A006", "first_name": "Tomás", "last_name": "Reyes",
     "title": "Chief Data Officer", "email": "t.reyes@bytestream.ai", "is_executive": 1},
    {"id": "C010", "account_id": "A007", "first_name": "Chris", "last_name": "Park",
     "title": "Head of Platform Engineering", "email": "c.park@devpipeline.io", "is_executive": 1},
    {"id": "C011", "account_id": "A007", "first_name": "Mei", "last_name": "Tanaka",
     "title": "Senior DevOps Architect", "email": "m.tanaka@devpipeline.io", "is_executive": 0},
    {"id": "C012", "account_id": "A008", "first_name": "Amanda", "last_name": "Foster",
     "title": "CTO", "email": "a.foster@nexgencloud.com", "is_executive": 1},
    {"id": "C013", "account_id": "A008", "first_name": "Greg", "last_name": "Lawson",
     "title": "VP Cloud Operations", "email": "g.lawson@nexgencloud.com", "is_executive": 1},
    {"id": "C014", "account_id": "A009", "first_name": "Elena", "last_name": "Vasquez",
     "title": "CTO", "email": "e.vasquez@packetforge.io", "is_executive": 1},
    {"id": "C015", "account_id": "A010", "first_name": "Sam", "last_name": "Okafor",
     "title": "Head of Research Engineering", "email": "s.okafor@cascadeai.com", "is_executive": 1},
    {"id": "C016", "account_id": "A011", "first_name": "Jessica", "last_name": "Huang",
     "title": "VP Platform", "email": "j.huang@stacknorth.io", "is_executive": 1},
    {"id": "C017", "account_id": "A011", "first_name": "Derek", "last_name": "Powell",
     "title": "K8s Platform Lead", "email": "d.powell@stacknorth.io", "is_executive": 0},
    {"id": "C018", "account_id": "A012", "first_name": "Marcus", "last_name": "Bell",
     "title": "CISO", "email": "m.bell@gridlock.io", "is_executive": 1},
    {"id": "C019", "account_id": "A013", "first_name": "Caitlin", "last_name": "Dunn",
     "title": "VP Engineering", "email": "c.dunn@longhorndata.com", "is_executive": 1},
    {"id": "C020", "account_id": "A014", "first_name": "Ryan", "last_name": "Kowalski",
     "title": "CTO", "email": "r.kowalski@alpinecode.com", "is_executive": 1},
    {"id": "C021", "account_id": "A015", "first_name": "Ava", "last_name": "Sterling",
     "title": "CEO", "email": "a.sterling@meshpoint.io", "is_executive": 1},
    {"id": "C022", "account_id": "A016", "first_name": "Victor", "last_name": "Hammond",
     "title": "CTO", "email": "v.hammond@edgesync.com", "is_executive": 1},
    {"id": "C023", "account_id": "A016", "first_name": "Layla", "last_name": "Pham",
     "title": "Director of Network Architecture", "email": "l.pham@edgesync.com", "is_executive": 0},
]

OPPORTUNITIES = [
    # Bay Area
    {"id": "O001", "account_id": "A002", "owner_id": "U001",
     "name": "CloudSphere - Multi-Cluster K8s Platform", "amount": 720_000,
     "probability": 80, "stage": "Negotiation/Review", "close_date": date(2026, 6, 30)},
    {"id": "O002", "account_id": "A002", "owner_id": "U001",
     "name": "CloudSphere - GitOps Tooling Add-on", "amount": 180_000,
     "probability": 75, "stage": "Proposal/Price Quote", "close_date": date(2026, 7, 15)},
    {"id": "O003", "account_id": "A004", "owner_id": "U004",
     "name": "SecureEdge - Zero Trust Runtime Security", "amount": 1_450_000,
     "probability": 75, "stage": "Proposal/Price Quote", "close_date": date(2026, 7, 15)},
    {"id": "O004", "account_id": "A004", "owner_id": "U004",
     "name": "SecureEdge - Threat Detection Add-on", "amount": 380_000,
     "probability": 85, "stage": "Negotiation/Review", "close_date": date(2026, 6, 20)},
    {"id": "O005", "account_id": "A001", "owner_id": "U003",
     "name": "Quantum Leap - GPU Cluster Orchestration", "amount": 890_000,
     "probability": 65, "stage": "Value Proposition", "close_date": date(2026, 8, 31)},
    {"id": "O006", "account_id": "A001", "owner_id": "U003",
     "name": "Quantum Leap - MLOps Pipeline Platform", "amount": 340_000,
     "probability": 55, "stage": "Needs Analysis", "close_date": date(2026, 9, 30)},
    {"id": "O007", "account_id": "A008", "owner_id": "U002",
     "name": "NexGen Cloud - Hybrid Cloud Migration", "amount": 2_100_000,
     "probability": 70, "stage": "Proposal/Price Quote", "close_date": date(2026, 7, 31)},
    {"id": "O008", "account_id": "A008", "owner_id": "U002",
     "name": "NexGen Cloud - FinOps Platform", "amount": 420_000,
     "probability": 60, "stage": "Value Proposition", "close_date": date(2026, 9, 15)},
    {"id": "O009", "account_id": "A007", "owner_id": "U001",
     "name": "DevPipeline - Enterprise K8s License Expansion", "amount": 540_000,
     "probability": 90, "stage": "Negotiation/Review", "close_date": date(2026, 6, 15)},
    {"id": "O010", "account_id": "A005", "owner_id": "U002",
     "name": "HorizonScale - Cloud-Native Platform", "amount": 380_000,
     "probability": 55, "stage": "Needs Analysis", "close_date": date(2026, 9, 30)},
    {"id": "O011", "account_id": "A003", "owner_id": "U006",
     "name": "DataVault - Distributed Storage Tier", "amount": 660_000,
     "probability": 60, "stage": "Proposal/Price Quote", "close_date": date(2026, 8, 15)},
    {"id": "O012", "account_id": "A006", "owner_id": "U003",
     "name": "ByteStream - ML Inference Pipeline", "amount": 290_000,
     "probability": 45, "stage": "Qualification", "close_date": date(2026, 10, 31)},
    # Seattle
    {"id": "O013", "account_id": "A011", "owner_id": "U001",
     "name": "StackNorth - K8s Enterprise Platform", "amount": 980_000,
     "probability": 75, "stage": "Proposal/Price Quote", "close_date": date(2026, 8, 31)},
    {"id": "O014", "account_id": "A011", "owner_id": "U002",
     "name": "StackNorth - DR Cluster Setup", "amount": 260_000,
     "probability": 70, "stage": "Value Proposition", "close_date": date(2026, 9, 30)},
    {"id": "O015", "account_id": "A009", "owner_id": "U005",
     "name": "PacketForge - SD-WAN Controller", "amount": 520_000,
     "probability": 50, "stage": "Needs Analysis", "close_date": date(2026, 10, 15)},
    {"id": "O016", "account_id": "A010", "owner_id": "U003",
     "name": "CascadeAI - Training Cluster Orchestration", "amount": 410_000,
     "probability": 40, "stage": "Qualification", "close_date": date(2026, 11, 30)},
    # Austin
    {"id": "O017", "account_id": "A012", "owner_id": "U004",
     "name": "GridLock - SOC Automation Platform", "amount": 1_100_000,
     "probability": 80, "stage": "Negotiation/Review", "close_date": date(2026, 6, 30)},
    {"id": "O018", "account_id": "A012", "owner_id": "U004",
     "name": "GridLock - Vulnerability Management Add-on", "amount": 280_000,
     "probability": 75, "stage": "Proposal/Price Quote", "close_date": date(2026, 7, 31)},
    {"id": "O019", "account_id": "A013", "owner_id": "U006",
     "name": "LonghornData - Flash Storage Tier", "amount": 195_000,
     "probability": 55, "stage": "Value Proposition", "close_date": date(2026, 10, 31)},
    # Denver / Boulder
    {"id": "O020", "account_id": "A014", "owner_id": "U002",
     "name": "AlpineCode - Cloud Infrastructure Refresh", "amount": 670_000,
     "probability": 65, "stage": "Proposal/Price Quote", "close_date": date(2026, 8, 31)},
    {"id": "O021", "account_id": "A015", "owner_id": "U001",
     "name": "MeshPoint - K8s Edge Orchestration", "amount": 310_000,
     "probability": 45, "stage": "Needs Analysis", "close_date": date(2026, 10, 31)},
    # New York
    {"id": "O022", "account_id": "A016", "owner_id": "U005",
     "name": "EdgeSync - Network Fabric Upgrade", "amount": 840_000,
     "probability": 35, "stage": "Qualification", "close_date": date(2026, 12, 15)},
    {"id": "O023", "account_id": "A016", "owner_id": "U005",
     "name": "EdgeSync - Observability Platform", "amount": 220_000,
     "probability": 30, "stage": "Prospecting", "close_date": date(2027, 1, 31)},
    {"id": "O024", "account_id": "A003", "owner_id": "U006",
     "name": "DataVault - Backup & Archive Solution", "amount": 230_000,
     "probability": 65, "stage": "Negotiation/Review", "close_date": date(2026, 6, 30)},
]

CONFERENCES = [
    {"id": "CF001", "name": "KubeCon NA 2026", "city": "Chicago", "state": "IL",
     "start_date": date(2026, 11, 9), "end_date": date(2026, 11, 12), "ebx_slots": 8,
     "description": "Largest Kubernetes conference in North America"},
    {"id": "CF002", "name": "DockerCon SF 2026", "city": "San Francisco", "state": "CA",
     "start_date": date(2026, 9, 22), "end_date": date(2026, 9, 24), "ebx_slots": 6,
     "description": "Container and cloud-native technologies"},
    {"id": "CF003", "name": "AWS re:Invent 2026", "city": "Las Vegas", "state": "NV",
     "start_date": date(2026, 11, 30), "end_date": date(2026, 12, 4), "ebx_slots": 10,
     "description": "Amazon Web Services annual conference"},
]

ATTENDEES = [
    # KubeCon NA - Chicago
    {"conf_id": "CF001", "user_id": "U001", "role": "Sales Lead",
     "hotel": "Marriott Chicago Downtown", "hotel_addr": "540 N Michigan Ave, Chicago, IL 60611",
     "check_in": date(2026, 11, 8), "check_out": date(2026, 11, 13),
     "flight_in": "UA 234 · Nov 8 · ORD arrives 2:30 PM",
     "flight_out": "UA 237 · Nov 13 · Departs ORD 5:00 PM"},
    {"conf_id": "CF001", "user_id": "U003", "role": "AI/ML Solutions Lead",
     "hotel": "Marriott Chicago Downtown", "hotel_addr": "540 N Michigan Ave, Chicago, IL 60611",
     "check_in": date(2026, 11, 9), "check_out": date(2026, 11, 12),
     "flight_in": "AA 881 · Nov 9 · ORD arrives 10:00 AM",
     "flight_out": "AA 884 · Nov 12 · Departs ORD 7:00 PM"},
    {"conf_id": "CF001", "user_id": "U004", "role": "Security Specialist",
     "hotel": "Hyatt Regency Chicago", "hotel_addr": "151 E Wacker Dr, Chicago, IL 60601",
     "check_in": date(2026, 11, 9), "check_out": date(2026, 11, 12),
     "flight_in": "DL 412 · Nov 9 · ORD arrives 12:00 PM",
     "flight_out": "DL 415 · Nov 12 · Departs ORD 6:30 PM"},
    # DockerCon SF
    {"conf_id": "CF002", "user_id": "U001", "role": "Sales Lead",
     "hotel": "Hotel Nikko San Francisco", "hotel_addr": "222 Mason St, San Francisco, CA 94102",
     "check_in": date(2026, 9, 21), "check_out": date(2026, 9, 25),
     "flight_in": "DL 201 · Sep 21 · SFO arrives 11:00 AM",
     "flight_out": "DL 204 · Sep 25 · Departs SFO 4:00 PM"},
    {"conf_id": "CF002", "user_id": "U002", "role": "Cloud Architecture Lead",
     "hotel": "Hotel Nikko San Francisco", "hotel_addr": "222 Mason St, San Francisco, CA 94102",
     "check_in": date(2026, 9, 22), "check_out": date(2026, 9, 24),
     "flight_in": "AA 567 · Sep 22 · SFO arrives 9:00 AM",
     "flight_out": "AA 570 · Sep 24 · Departs SFO 6:00 PM"},
    # AWS re:Invent - Las Vegas
    {"conf_id": "CF003", "user_id": "U001", "role": "Sales Lead",
     "hotel": "The Venetian Resort", "hotel_addr": "3355 Las Vegas Blvd S, Las Vegas, NV 89109",
     "check_in": date(2026, 11, 29), "check_out": date(2026, 12, 5),
     "flight_in": "SW 112 · Nov 29 · LAS arrives 1:00 PM",
     "flight_out": "SW 115 · Dec 5 · Departs LAS 3:00 PM"},
    {"conf_id": "CF003", "user_id": "U002", "role": "Cloud Infrastructure Lead",
     "hotel": "MGM Grand Las Vegas", "hotel_addr": "3799 Las Vegas Blvd S, Las Vegas, NV 89109",
     "check_in": date(2026, 11, 30), "check_out": date(2026, 12, 4),
     "flight_in": "UA 891 · Nov 30 · LAS arrives 10:00 AM",
     "flight_out": "UA 894 · Dec 4 · Departs LAS 7:00 PM"},
    {"conf_id": "CF003", "user_id": "U003", "role": "AI/ML Demo Lead",
     "hotel": "The Venetian Resort", "hotel_addr": "3355 Las Vegas Blvd S, Las Vegas, NV 89109",
     "check_in": date(2026, 11, 30), "check_out": date(2026, 12, 4),
     "flight_in": "AA 431 · Nov 30 · LAS arrives 2:00 PM",
     "flight_out": "AA 434 · Dec 4 · Departs LAS 5:00 PM"},
]
