from datetime import date
from .auth import hash_password

TENANT_NAME = "Apex Healthcare Solutions"

USERS = [
    {"id": "U001", "name": "Emily Park", "email": "admin@apexhealth.tech",
     "title": "VP Sales Engineering", "specialty": "Security",
     "slack_handle": "epark", "role": "admin",
     "password_hash": hash_password("Apex123!")},
    {"id": "U002", "name": "John Wilson", "email": "j.wilson@apexhealth.tech",
     "title": "AI/ML Healthcare Architect", "specialty": "AI/ML",
     "slack_handle": "jwilson", "role": "user",
     "password_hash": hash_password("Apex123!")},
    {"id": "U003", "name": "Maria Santos", "email": "m.santos@apexhealth.tech",
     "title": "Cloud Infrastructure Engineer", "specialty": "Cloud Infrastructure",
     "slack_handle": "msantos", "role": "user",
     "password_hash": hash_password("Apex123!")},
    {"id": "U004", "name": "Kevin Lee", "email": "k.lee@apexhealth.tech",
     "title": "Medical Imaging Storage Lead", "specialty": "Storage",
     "slack_handle": "klee", "role": "user",
     "password_hash": hash_password("Apex123!")},
    {"id": "U005", "name": "Amanda Foster", "email": "a.foster@apexhealth.tech",
     "title": "Clinical Network Specialist", "specialty": "Networking",
     "slack_handle": "afoster", "role": "user",
     "password_hash": hash_password("Apex123!")},
    {"id": "U006", "name": "Chris Nguyen", "email": "c.nguyen@apexhealth.tech",
     "title": "K8s Platform Engineer", "specialty": "Kubernetes Platform",
     "slack_handle": "cnguyen", "role": "user",
     "password_hash": hash_password("Apex123!")},
]

ACCOUNTS = [
    {"id": "A001", "name": "Memorial Health Systems", "billing_city": "Chicago",
     "billing_state": "IL", "industry": "Hospital System", "annual_revenue": 8_400_000_000,
     "account_type": "Customer", "product_interest": "AI/ML", "owner_id": "U002"},
    {"id": "A002", "name": "Midwest Pharma Research", "billing_city": "Indianapolis",
     "billing_state": "IN", "industry": "Pharmaceuticals", "annual_revenue": 2_900_000_000,
     "account_type": "Customer", "product_interest": "Storage", "owner_id": "U004"},
    {"id": "A003", "name": "CareConnect Networks", "billing_city": "Chicago",
     "billing_state": "IL", "industry": "Healthcare IT", "annual_revenue": 420_000_000,
     "account_type": "Prospect", "product_interest": "Networking", "owner_id": "U005"},
    {"id": "A004", "name": "BioGenesis Labs", "billing_city": "Milwaukee",
     "billing_state": "WI", "industry": "Biotechnology", "annual_revenue": 750_000_000,
     "account_type": "Prospect", "product_interest": "AI/ML", "owner_id": "U002"},
    {"id": "A005", "name": "HealthFirst Insurance", "billing_city": "Chicago",
     "billing_state": "IL", "industry": "Health Insurance", "annual_revenue": 5_600_000_000,
     "account_type": "Customer", "product_interest": "Security", "owner_id": "U001"},
    {"id": "A006", "name": "Precision Medical Group", "billing_city": "Detroit",
     "billing_state": "MI", "industry": "Medical Devices", "annual_revenue": 1_100_000_000,
     "account_type": "Prospect", "product_interest": "AI/ML", "owner_id": "U002"},
    {"id": "A007", "name": "Great Lakes Children's Hospital", "billing_city": "Cleveland",
     "billing_state": "OH", "industry": "Pediatric Healthcare", "annual_revenue": 1_800_000_000,
     "account_type": "Customer", "product_interest": "Security", "owner_id": "U001"},
    {"id": "A008", "name": "Midwest Medical Devices", "billing_city": "Chicago",
     "billing_state": "IL", "industry": "Medical Devices", "annual_revenue": 680_000_000,
     "account_type": "Prospect", "product_interest": "Kubernetes Platform", "owner_id": "U006"},
]

CONTACTS = [
    {"id": "C001", "account_id": "A001", "first_name": "Dr. Patricia", "last_name": "Nguyen",
     "title": "CIO", "email": "p.nguyen@memorialhealth.org", "is_executive": 1},
    {"id": "C002", "account_id": "A002", "first_name": "Richard", "last_name": "Coleman",
     "title": "VP IT Infrastructure", "email": "r.coleman@midwestpharma.com", "is_executive": 1},
    {"id": "C003", "account_id": "A005", "first_name": "Susan", "last_name": "Blake",
     "title": "CISO", "email": "s.blake@healthfirst.com", "is_executive": 1},
    {"id": "C004", "account_id": "A007", "first_name": "Dr. Michael", "last_name": "Okonkwo",
     "title": "CTO", "email": "m.okonkwo@greatlakeschildrens.org", "is_executive": 1},
    {"id": "C005", "account_id": "A004", "first_name": "Natalie", "last_name": "Stern",
     "title": "Head of Genomics IT", "email": "n.stern@biogenesis.com", "is_executive": 1},
]

OPPORTUNITIES = [
    {"id": "O001", "account_id": "A001", "owner_id": "U002",
     "name": "Memorial Health - AI Clinical Decision Support", "amount": 3_200_000,
     "probability": 75, "stage": "Proposal/Price Quote", "close_date": date(2026, 7, 31)},
    {"id": "O002", "account_id": "A005", "owner_id": "U001",
     "name": "HealthFirst - HIPAA Compliance Platform", "amount": 2_600_000,
     "probability": 85, "stage": "Negotiation/Review", "close_date": date(2026, 6, 30)},
    {"id": "O003", "account_id": "A002", "owner_id": "U004",
     "name": "Midwest Pharma - Genomics Data Storage Tier", "amount": 1_800_000,
     "probability": 70, "stage": "Proposal/Price Quote", "close_date": date(2026, 8, 15)},
    {"id": "O004", "account_id": "A007", "owner_id": "U001",
     "name": "Great Lakes Children's - Zero Trust Security", "amount": 1_400_000,
     "probability": 80, "stage": "Negotiation/Review", "close_date": date(2026, 6, 15)},
    {"id": "O005", "account_id": "A004", "owner_id": "U002",
     "name": "BioGenesis - ML Drug Discovery Pipeline", "amount": 950_000,
     "probability": 60, "stage": "Value Proposition", "close_date": date(2026, 9, 30)},
    {"id": "O006", "account_id": "A006", "owner_id": "U002",
     "name": "Precision Medical - AI Diagnostics Platform", "amount": 1_100_000,
     "probability": 55, "stage": "Needs Analysis", "close_date": date(2026, 10, 31)},
    {"id": "O007", "account_id": "A003", "owner_id": "U005",
     "name": "CareConnect - Clinical Network Refresh", "amount": 580_000,
     "probability": 65, "stage": "Proposal/Price Quote", "close_date": date(2026, 8, 31)},
    {"id": "O008", "account_id": "A008", "owner_id": "U006",
     "name": "Midwest Medical Devices - K8s IoT Platform", "amount": 720_000,
     "probability": 50, "stage": "Value Proposition", "close_date": date(2026, 11, 15)},
]

CONFERENCES = [
    {"id": "CF001", "name": "HIMSS 2026", "city": "Las Vegas", "state": "NV",
     "start_date": date(2026, 3, 9), "end_date": date(2026, 3, 13), "ebx_slots": 10,
     "description": "Healthcare Information and Management Systems Society annual conference"},
    {"id": "CF002", "name": "Health 2.0 Chicago 2026", "city": "Chicago", "state": "IL",
     "start_date": date(2026, 9, 10), "end_date": date(2026, 9, 12), "ebx_slots": 6,
     "description": "Digital health innovation and technology"},
    {"id": "CF003", "name": "Bio-IT World 2026", "city": "Boston", "state": "MA",
     "start_date": date(2026, 5, 12), "end_date": date(2026, 5, 15), "ebx_slots": 8,
     "description": "Life sciences and pharma IT conference"},
]
