from datetime import date
from .auth import hash_password

TENANT_NAME = "Meridian Financial Group"

USERS = [
    {"id": "U001", "name": "Sarah Chen", "email": "admin@meridian-fg.com",
     "title": "Director of Sales Engineering", "specialty": "Security",
     "slack_handle": "schen", "role": "admin",
     "password_hash": hash_password("Meridian123!")},
    {"id": "U002", "name": "James Porter", "email": "j.porter@meridian-fg.com",
     "title": "Network Solutions Architect", "specialty": "Networking",
     "slack_handle": "jporter", "role": "user",
     "password_hash": hash_password("Meridian123!")},
    {"id": "U003", "name": "Michelle Davis", "email": "m.davis@meridian-fg.com",
     "title": "Compliance & Security Engineer", "specialty": "Security",
     "slack_handle": "mdavis", "role": "user",
     "password_hash": hash_password("Meridian123!")},
    {"id": "U004", "name": "Robert Kim", "email": "r.kim@meridian-fg.com",
     "title": "Cloud Infrastructure Lead", "specialty": "Cloud Infrastructure",
     "slack_handle": "rkim", "role": "user",
     "password_hash": hash_password("Meridian123!")},
    {"id": "U005", "name": "Lisa Thompson", "email": "l.thompson@meridian-fg.com",
     "title": "AI/ML Solutions Engineer", "specialty": "AI/ML",
     "slack_handle": "lthompson", "role": "user",
     "password_hash": hash_password("Meridian123!")},
    {"id": "U006", "name": "Daniel Park", "email": "d.park@meridian-fg.com",
     "title": "Storage & Data Engineer", "specialty": "Storage",
     "slack_handle": "dpark", "role": "user",
     "password_hash": hash_password("Meridian123!")},
]

ACCOUNTS = [
    {"id": "A001", "name": "Manhattan Capital Bank", "billing_city": "New York",
     "billing_state": "NY", "industry": "Banking", "annual_revenue": 4_200_000_000,
     "account_type": "Customer", "product_interest": "Security", "owner_id": "U003"},
    {"id": "A002", "name": "Apex Trading Systems", "billing_city": "New York",
     "billing_state": "NY", "industry": "Financial Trading", "annual_revenue": 890_000_000,
     "account_type": "Customer", "product_interest": "Networking", "owner_id": "U002"},
    {"id": "A003", "name": "Liberty Insurance Corp", "billing_city": "Boston",
     "billing_state": "MA", "industry": "Insurance", "annual_revenue": 3_100_000_000,
     "account_type": "Prospect", "product_interest": "Cloud Infrastructure", "owner_id": "U004"},
    {"id": "A004", "name": "NorthStar Wealth Management", "billing_city": "Chicago",
     "billing_state": "IL", "industry": "Wealth Management", "annual_revenue": 720_000_000,
     "account_type": "Prospect", "product_interest": "AI/ML", "owner_id": "U005"},
    {"id": "A005", "name": "Pacific Exchange Group", "billing_city": "San Francisco",
     "billing_state": "CA", "industry": "Securities Exchange", "annual_revenue": 1_800_000_000,
     "account_type": "Customer", "product_interest": "Kubernetes Platform", "owner_id": "U001"},
    {"id": "A006", "name": "Atlantic Fintech Partners", "billing_city": "Miami",
     "billing_state": "FL", "industry": "FinTech", "annual_revenue": 340_000_000,
     "account_type": "Prospect", "product_interest": "Networking", "owner_id": "U002"},
    {"id": "A007", "name": "Summit Risk Analytics", "billing_city": "New York",
     "billing_state": "NY", "industry": "Risk Management", "annual_revenue": 560_000_000,
     "account_type": "Prospect", "product_interest": "AI/ML", "owner_id": "U005"},
    {"id": "A008", "name": "Cornerstone Payment Systems", "billing_city": "Dallas",
     "billing_state": "TX", "industry": "Payment Processing", "annual_revenue": 1_100_000_000,
     "account_type": "Customer", "product_interest": "Security", "owner_id": "U003"},
]

CONTACTS = [
    {"id": "C001", "account_id": "A001", "first_name": "William", "last_name": "Hartley",
     "title": "CISO", "email": "w.hartley@manhattancapital.com", "is_executive": 1},
    {"id": "C002", "account_id": "A002", "first_name": "Victoria", "last_name": "Zhao",
     "title": "CTO", "email": "v.zhao@apextrading.com", "is_executive": 1},
    {"id": "C003", "account_id": "A003", "first_name": "Thomas", "last_name": "Reeves",
     "title": "VP Technology", "email": "t.reeves@libertyins.com", "is_executive": 1},
    {"id": "C004", "account_id": "A005", "first_name": "Angela", "last_name": "Morrison",
     "title": "Head of Engineering", "email": "a.morrison@pacificexchange.com", "is_executive": 1},
    {"id": "C005", "account_id": "A008", "first_name": "Kevin", "last_name": "Walsh",
     "title": "CTO", "email": "k.walsh@cornerstonepay.com", "is_executive": 1},
]

OPPORTUNITIES = [
    {"id": "O001", "account_id": "A001", "owner_id": "U003",
     "name": "Manhattan Capital - SOC2 Compliance Platform", "amount": 2_800_000,
     "probability": 80, "stage": "Negotiation/Review", "close_date": date(2026, 6, 30)},
    {"id": "O002", "account_id": "A002", "owner_id": "U002",
     "name": "Apex Trading - Ultra-Low Latency Network Upgrade", "amount": 1_900_000,
     "probability": 75, "stage": "Proposal/Price Quote", "close_date": date(2026, 7, 31)},
    {"id": "O003", "account_id": "A005", "owner_id": "U001",
     "name": "Pacific Exchange - K8s Trading Platform", "amount": 3_400_000,
     "probability": 70, "stage": "Proposal/Price Quote", "close_date": date(2026, 8, 15)},
    {"id": "O004", "account_id": "A008", "owner_id": "U003",
     "name": "Cornerstone Pay - PCI-DSS Security Stack", "amount": 1_650_000,
     "probability": 85, "stage": "Negotiation/Review", "close_date": date(2026, 6, 15)},
    {"id": "O005", "account_id": "A004", "owner_id": "U005",
     "name": "NorthStar - AI Portfolio Risk Engine", "amount": 980_000,
     "probability": 60, "stage": "Value Proposition", "close_date": date(2026, 9, 30)},
    {"id": "O006", "account_id": "A003", "owner_id": "U004",
     "name": "Liberty Insurance - Hybrid Cloud Migration", "amount": 2_200_000,
     "probability": 55, "stage": "Needs Analysis", "close_date": date(2026, 10, 31)},
    {"id": "O007", "account_id": "A007", "owner_id": "U005",
     "name": "Summit Risk - ML Fraud Detection", "amount": 740_000,
     "probability": 65, "stage": "Proposal/Price Quote", "close_date": date(2026, 8, 31)},
    {"id": "O008", "account_id": "A006", "owner_id": "U002",
     "name": "Atlantic Fintech - SD-WAN Deployment", "amount": 490_000,
     "probability": 50, "stage": "Value Proposition", "close_date": date(2026, 11, 30)},
]

CONFERENCES = [
    {"id": "CF001", "name": "FinTech Summit NY 2026", "city": "New York", "state": "NY",
     "start_date": date(2026, 6, 9), "end_date": date(2026, 6, 11), "ebx_slots": 8,
     "description": "Premier fintech and banking technology conference"},
    {"id": "CF002", "name": "Money20/20 Vegas 2026", "city": "Las Vegas", "state": "NV",
     "start_date": date(2026, 10, 26), "end_date": date(2026, 10, 29), "ebx_slots": 10,
     "description": "Global fintech and payments event"},
    {"id": "CF003", "name": "Sibos 2026", "city": "Toronto", "state": "ON",
     "start_date": date(2026, 10, 12), "end_date": date(2026, 10, 15), "ebx_slots": 6,
     "description": "SWIFT global banking operations conference"},
]
