from datetime import date
from .auth import hash_password

TENANT_NAME = "NovaTech Systems"

USERS = [
    {"id": "U001", "name": "Marcus Rodriguez", "email": "admin@novatech.io",
     "title": "VP Sales Engineering", "specialty": "Kubernetes Platform",
     "slack_handle": "mrodriguez", "role": "admin",
     "password_hash": hash_password("NovaTech123!")},
    {"id": "U002", "name": "Jennifer Wu", "email": "j.wu@novatech.io",
     "title": "Cloud Architect", "specialty": "Cloud Infrastructure",
     "slack_handle": "jwu", "role": "user",
     "password_hash": hash_password("NovaTech123!")},
    {"id": "U003", "name": "Alex Kim", "email": "a.kim@novatech.io",
     "title": "AI/ML Solutions Engineer", "specialty": "AI/ML",
     "slack_handle": "akim", "role": "user",
     "password_hash": hash_password("NovaTech123!")},
    {"id": "U004", "name": "David Torres", "email": "d.torres@novatech.io",
     "title": "Security Architect", "specialty": "Security",
     "slack_handle": "dtorres", "role": "user",
     "password_hash": hash_password("NovaTech123!")},
    {"id": "U005", "name": "Rachel Chen", "email": "r.chen@novatech.io",
     "title": "Networking Specialist", "specialty": "Networking",
     "slack_handle": "rchen", "role": "user",
     "password_hash": hash_password("NovaTech123!")},
    {"id": "U006", "name": "Tyler Johnson", "email": "t.johnson@novatech.io",
     "title": "Storage Engineer", "specialty": "Storage",
     "slack_handle": "tjohnson", "role": "user",
     "password_hash": hash_password("NovaTech123!")},
]

ACCOUNTS = [
    {"id": "A001", "name": "Quantum Leap Technologies", "billing_city": "San Francisco",
     "billing_state": "CA", "industry": "Artificial Intelligence", "annual_revenue": 85_000_000,
     "account_type": "Customer", "product_interest": "AI/ML", "owner_id": "U003"},
    {"id": "A002", "name": "CloudSphere Inc", "billing_city": "San Jose",
     "billing_state": "CA", "industry": "Cloud Software", "annual_revenue": 210_000_000,
     "account_type": "Customer", "product_interest": "Kubernetes Platform", "owner_id": "U001"},
    {"id": "A003", "name": "DataVault Systems", "billing_city": "Palo Alto",
     "billing_state": "CA", "industry": "Data Management", "annual_revenue": 140_000_000,
     "account_type": "Prospect", "product_interest": "Storage", "owner_id": "U006"},
    {"id": "A004", "name": "SecureEdge Networks", "billing_city": "Mountain View",
     "billing_state": "CA", "industry": "Cybersecurity", "annual_revenue": 320_000_000,
     "account_type": "Customer", "product_interest": "Security", "owner_id": "U004"},
    {"id": "A005", "name": "HorizonScale", "billing_city": "San Francisco",
     "billing_state": "CA", "industry": "Infrastructure SaaS", "annual_revenue": 95_000_000,
     "account_type": "Prospect", "product_interest": "Cloud Infrastructure", "owner_id": "U002"},
    {"id": "A006", "name": "ByteStream Analytics", "billing_city": "Oakland",
     "billing_state": "CA", "industry": "Data Analytics", "annual_revenue": 67_000_000,
     "account_type": "Prospect", "product_interest": "AI/ML", "owner_id": "U003"},
    {"id": "A007", "name": "DevPipeline Co", "billing_city": "Sunnyvale",
     "billing_state": "CA", "industry": "DevOps Tooling", "annual_revenue": 180_000_000,
     "account_type": "Customer", "product_interest": "Kubernetes Platform", "owner_id": "U001"},
    {"id": "A008", "name": "NexGen Cloud", "billing_city": "Santa Clara",
     "billing_state": "CA", "industry": "Cloud Services", "annual_revenue": 450_000_000,
     "account_type": "Customer", "product_interest": "Cloud Infrastructure", "owner_id": "U002"},
]

CONTACTS = [
    {"id": "C001", "account_id": "A001", "first_name": "Priya", "last_name": "Patel",
     "title": "CTO", "email": "ppatel@quantumleap.io", "is_executive": 1},
    {"id": "C002", "account_id": "A002", "first_name": "Nathan", "last_name": "Brooks",
     "title": "VP Engineering", "email": "nbrooks@cloudsphere.com", "is_executive": 1},
    {"id": "C003", "account_id": "A004", "first_name": "Zoe", "last_name": "Martinez",
     "title": "CISO", "email": "zmartinez@secureedge.com", "is_executive": 1},
    {"id": "C004", "account_id": "A007", "first_name": "Chris", "last_name": "Park",
     "title": "Head of Platform Eng", "email": "cpark@devpipeline.io", "is_executive": 1},
    {"id": "C005", "account_id": "A008", "first_name": "Amanda", "last_name": "Foster",
     "title": "CTO", "email": "afoster@nexgencloud.com", "is_executive": 1},
]

OPPORTUNITIES = [
    {"id": "O001", "account_id": "A002", "owner_id": "U001",
     "name": "CloudSphere - Multi-Cluster K8s Platform", "amount": 720_000,
     "probability": 80, "stage": "Negotiation/Review", "close_date": date(2026, 6, 30)},
    {"id": "O002", "account_id": "A004", "owner_id": "U004",
     "name": "SecureEdge - Zero Trust Runtime Security", "amount": 1_450_000,
     "probability": 75, "stage": "Proposal/Price Quote", "close_date": date(2026, 7, 15)},
    {"id": "O003", "account_id": "A001", "owner_id": "U003",
     "name": "Quantum Leap - GPU Cluster Orchestration", "amount": 890_000,
     "probability": 65, "stage": "Value Proposition", "close_date": date(2026, 8, 31)},
    {"id": "O004", "account_id": "A008", "owner_id": "U002",
     "name": "NexGen Cloud - Hybrid Cloud Migration", "amount": 2_100_000,
     "probability": 70, "stage": "Proposal/Price Quote", "close_date": date(2026, 7, 31)},
    {"id": "O005", "account_id": "A007", "owner_id": "U001",
     "name": "DevPipeline - Enterprise K8s License Expansion", "amount": 540_000,
     "probability": 90, "stage": "Negotiation/Review", "close_date": date(2026, 6, 15)},
    {"id": "O006", "account_id": "A005", "owner_id": "U002",
     "name": "HorizonScale - Cloud-Native Platform", "amount": 380_000,
     "probability": 55, "stage": "Needs Analysis", "close_date": date(2026, 9, 30)},
    {"id": "O007", "account_id": "A003", "owner_id": "U006",
     "name": "DataVault - Distributed Storage Tier", "amount": 660_000,
     "probability": 60, "stage": "Proposal/Price Quote", "close_date": date(2026, 8, 15)},
    {"id": "O008", "account_id": "A006", "owner_id": "U003",
     "name": "ByteStream - ML Inference Pipeline", "amount": 290_000,
     "probability": 50, "stage": "Value Proposition", "close_date": date(2026, 10, 31)},
]

CONFERENCES = [
    {"id": "CF001", "name": "KubeCon NA 2026", "city": "Chicago", "state": "IL",
     "start_date": date(2026, 11, 9), "end_date": date(2026, 11, 12), "ebx_slots": 8,
     "description": "Largest Kubernetes conference in North America"},
    {"id": "CF002", "name": "DockerCon SF 2026", "city": "San Francisco", "state": "CA",
     "start_date": date(2026, 9, 22), "end_date": date(2026, 9, 24), "ebx_slots": 6,
     "description": "Container and cloud-native technologies"},
    {"id": "CF003", "name": "AWS re:Invent 2026", "city": "Las Vegas", "state": "NV",
     "start_date": date(2026, 11, 30), "end_date": date(2026, 12, 4), "ebx_slots": 10,
     "description": "Amazon Web Services annual conference"},
]
