from datetime import date
from .auth import hash_password

TENANT_NAME = "Apex Healthcare Solutions"

USERS = [
    {"id": "U001", "name": "Emily Park", "email": "admin@apexhealth.tech",
     "title": "VP Sales Engineering", "specialty": "Security",
     "slack_handle": "epark", "role": "admin",
     "password_hash": hash_password("Apex123!")},
    {"id": "U002", "name": "John Wilson", "email": "j.wilson@apexhealth.tech",
     "title": "AI/ML Healthcare Architect", "specialty": "AI/ML",
     "slack_handle": "jwilson", "role": "user",
     "password_hash": hash_password("Apex123!")},
    {"id": "U003", "name": "Maria Santos", "email": "m.santos@apexhealth.tech",
     "title": "Cloud Infrastructure Engineer", "specialty": "Cloud Infrastructure",
     "slack_handle": "msantos", "role": "user",
     "password_hash": hash_password("Apex123!")},
    {"id": "U004", "name": "Kevin Lee", "email": "k.lee@apexhealth.tech",
     "title": "Medical Imaging Storage Lead", "specialty": "Storage",
     "slack_handle": "klee", "role": "user",
     "password_hash": hash_password("Apex123!")},
    {"id": "U005", "name": "Amanda Foster", "email": "a.foster@apexhealth.tech",
     "title": "Clinical Network Specialist", "specialty": "Networking",
     "slack_handle": "afoster", "role": "user",
     "password_hash": hash_password("Apex123!")},
    {"id": "U006", "name": "Chris Nguyen", "email": "c.nguyen@apexhealth.tech",
     "title": "K8s Platform Engineer", "specialty": "Kubernetes Platform",
     "slack_handle": "cnguyen", "role": "user",
     "password_hash": hash_password("Apex123!")},
]

ACCOUNTS = [
    # Chicago
    {"id": "A001", "name": "Memorial Health Systems", "billing_city": "Chicago",
     "billing_state": "IL", "industry": "Hospital System", "annual_revenue": 8_400_000_000,
     "account_type": "Customer", "product_interest": "AI/ML", "owner_id": "U002"},
    {"id": "A002", "name": "CareConnect Networks", "billing_city": "Chicago",
     "billing_state": "IL", "industry": "Healthcare IT", "annual_revenue": 420_000_000,
     "account_type": "Prospect", "product_interest": "Networking", "owner_id": "U005"},
    {"id": "A003", "name": "HealthFirst Insurance", "billing_city": "Chicago",
     "billing_state": "IL", "industry": "Health Insurance", "annual_revenue": 5_600_000_000,
     "account_type": "Customer", "product_interest": "Security", "owner_id": "U001"},
    {"id": "A004", "name": "Midwest Medical Devices", "billing_city": "Chicago",
     "billing_state": "IL", "industry": "Medical Devices", "annual_revenue": 680_000_000,
     "account_type": "Prospect", "product_interest": "Kubernetes Platform", "owner_id": "U006"},
    # Indianapolis
    {"id": "A005", "name": "Midwest Pharma Research", "billing_city": "Indianapolis",
     "billing_state": "IN", "industry": "Pharmaceuticals", "annual_revenue": 2_900_000_000,
     "account_type": "Customer", "product_interest": "Storage", "owner_id": "U004"},
    {"id": "A006", "name": "Crossroads Health Network", "billing_city": "Indianapolis",
     "billing_state": "IN", "industry": "Hospital System", "annual_revenue": 3_200_000_000,
     "account_type": "Prospect", "product_interest": "Cloud Infrastructure", "owner_id": "U003"},
    # Detroit / Michigan
    {"id": "A007", "name": "Precision Medical Group", "billing_city": "Detroit",
     "billing_state": "MI", "industry": "Medical Devices", "annual_revenue": 1_100_000_000,
     "account_type": "Prospect", "product_interest": "AI/ML", "owner_id": "U002"},
    {"id": "A008", "name": "Great Lakes Imaging Center", "billing_city": "Ann Arbor",
     "billing_state": "MI", "industry": "Diagnostic Imaging", "annual_revenue": 380_000_000,
     "account_type": "Customer", "product_interest": "Storage", "owner_id": "U004"},
    # Cleveland / Ohio
    {"id": "A009", "name": "Great Lakes Children's Hospital", "billing_city": "Cleveland",
     "billing_state": "OH", "industry": "Pediatric Healthcare", "annual_revenue": 1_800_000_000,
     "account_type": "Customer", "product_interest": "Security", "owner_id": "U001"},
    {"id": "A010", "name": "OhioHealth Systems", "billing_city": "Columbus",
     "billing_state": "OH", "industry": "Hospital System", "annual_revenue": 4_100_000_000,
     "account_type": "Prospect", "product_interest": "Kubernetes Platform", "owner_id": "U006"},
    # Milwaukee / Wisconsin
    {"id": "A011", "name": "BioGenesis Labs", "billing_city": "Milwaukee",
     "billing_state": "WI", "industry": "Biotechnology", "annual_revenue": 750_000_000,
     "account_type": "Prospect", "product_interest": "AI/ML", "owner_id": "U002"},
    {"id": "A012", "name": "Northshore Surgical Partners", "billing_city": "Milwaukee",
     "billing_state": "WI", "industry": "Surgical Services", "annual_revenue": 620_000_000,
     "account_type": "Customer", "product_interest": "Networking", "owner_id": "U005"},
    # Minneapolis
    {"id": "A013", "name": "North Star Medical Center", "billing_city": "Minneapolis",
     "billing_state": "MN", "industry": "Hospital System", "annual_revenue": 6_200_000_000,
     "account_type": "Customer", "product_interest": "AI/ML", "owner_id": "U002"},
    {"id": "A014", "name": "Twin Cities Pharma", "billing_city": "Minneapolis",
     "billing_state": "MN", "industry": "Pharmaceuticals", "annual_revenue": 1_400_000_000,
     "account_type": "Prospect", "product_interest": "Storage", "owner_id": "U004"},
    # St. Louis
    {"id": "A015", "name": "Gateway Health Alliance", "billing_city": "St. Louis",
     "billing_state": "MO", "industry": "Health Network", "annual_revenue": 2_800_000_000,
     "account_type": "Prospect", "product_interest": "Cloud Infrastructure", "owner_id": "U003"},
    # Pittsburgh
    {"id": "A016", "name": "Steel City Medical Center", "billing_city": "Pittsburgh",
     "billing_state": "PA", "industry": "Academic Medical Center", "annual_revenue": 3_500_000_000,
     "account_type": "Customer", "product_interest": "AI/ML", "owner_id": "U002"},
]

CONTACTS = [
    {"id": "C001", "account_id": "A001", "first_name": "Dr. Patricia", "last_name": "Nguyen",
     "title": "CIO", "email": "p.nguyen@memorialhealth.org", "is_executive": 1},
    {"id": "C002", "account_id": "A001", "first_name": "James", "last_name": "Kowalski",
     "title": "VP Digital Health", "email": "j.kowalski@memorialhealth.org", "is_executive": 0},
    {"id": "C003", "account_id": "A002", "first_name": "Laura", "last_name": "Simmons",
     "title": "CTO", "email": "l.simmons@careconnect.com", "is_executive": 1},
    {"id": "C004", "account_id": "A003", "first_name": "Susan", "last_name": "Blake",
     "title": "CISO", "email": "s.blake@healthfirst.com", "is_executive": 1},
    {"id": "C005", "account_id": "A003", "first_name": "Paul", "last_name": "Winters",
     "title": "Director of IT Security", "email": "p.winters@healthfirst.com", "is_executive": 0},
    {"id": "C006", "account_id": "A004", "first_name": "Grace", "last_name": "Chen",
     "title": "VP Engineering", "email": "g.chen@midwestmeddev.com", "is_executive": 1},
    {"id": "C007", "account_id": "A005", "first_name": "Richard", "last_name": "Coleman",
     "title": "VP IT Infrastructure", "email": "r.coleman@midwestpharma.com", "is_executive": 1},
    {"id": "C008", "account_id": "A005", "first_name": "Teri", "last_name": "Huang",
     "title": "Head of Research Computing", "email": "t.huang@midwestpharma.com", "is_executive": 0},
    {"id": "C009", "account_id": "A006", "first_name": "Dr. Samuel", "last_name": "Obi",
     "title": "CIO", "email": "s.obi@crossroadshealth.org", "is_executive": 1},
    {"id": "C010", "account_id": "A007", "first_name": "Karen", "last_name": "Finley",
     "title": "Head of R&D IT", "email": "k.finley@precisionmedical.com", "is_executive": 1},
    {"id": "C011", "account_id": "A008", "first_name": "Robert", "last_name": "Tran",
     "title": "VP Technology", "email": "r.tran@greatlakesimaging.com", "is_executive": 1},
    {"id": "C012", "account_id": "A009", "first_name": "Dr. Michael", "last_name": "Okonkwo",
     "title": "CTO", "email": "m.okonkwo@greatlakeschildrens.org", "is_executive": 1},
    {"id": "C013", "account_id": "A009", "first_name": "Diane", "last_name": "Sullivan",
     "title": "Director of Cybersecurity", "email": "d.sullivan@greatlakeschildrens.org", "is_executive": 0},
    {"id": "C014", "account_id": "A010", "first_name": "Dr. William", "last_name": "Bennett",
     "title": "CIO", "email": "w.bennett@ohiohealth.org", "is_executive": 1},
    {"id": "C015", "account_id": "A011", "first_name": "Natalie", "last_name": "Stern",
     "title": "Head of Genomics IT", "email": "n.stern@biogenesis.com", "is_executive": 1},
    {"id": "C016", "account_id": "A012", "first_name": "Frank", "last_name": "DiMaggio",
     "title": "VP IT", "email": "f.dimaggio@northshoresurgical.com", "is_executive": 1},
    {"id": "C017", "account_id": "A013", "first_name": "Dr. Angela", "last_name": "Ross",
     "title": "Chief Digital Officer", "email": "a.ross@northstarmedical.org", "is_executive": 1},
    {"id": "C018", "account_id": "A013", "first_name": "Marcus", "last_name": "Webb",
     "title": "Director of AI Initiatives", "email": "m.webb@northstarmedical.org", "is_executive": 0},
    {"id": "C019", "account_id": "A014", "first_name": "Julie", "last_name": "Olson",
     "title": "VP Informatics", "email": "j.olson@twincitespharma.com", "is_executive": 1},
    {"id": "C020", "account_id": "A015", "first_name": "Edward", "last_name": "Kane",
     "title": "CTO", "email": "e.kane@gatewayhealth.org", "is_executive": 1},
    {"id": "C021", "account_id": "A016", "first_name": "Dr. Catherine", "last_name": "Holt",
     "title": "CIO", "email": "c.holt@steelcitymed.org", "is_executive": 1},
    {"id": "C022", "account_id": "A016", "first_name": "Nathan", "last_name": "Perry",
     "title": "Head of Clinical AI", "email": "n.perry@steelcitymed.org", "is_executive": 0},
]

OPPORTUNITIES = [
    # Chicago
    {"id": "O001", "account_id": "A001", "owner_id": "U002",
     "name": "Memorial Health - AI Clinical Decision Support", "amount": 3_200_000,
     "probability": 75, "stage": "Proposal/Price Quote", "close_date": date(2026, 7, 31)},
    {"id": "O002", "account_id": "A001", "owner_id": "U002",
     "name": "Memorial Health - Radiology AI Platform", "amount": 1_400_000,
     "probability": 65, "stage": "Value Proposition", "close_date": date(2026, 9, 30)},
    {"id": "O003", "account_id": "A003", "owner_id": "U001",
     "name": "HealthFirst - HIPAA Compliance Platform", "amount": 2_600_000,
     "probability": 85, "stage": "Negotiation/Review", "close_date": date(2026, 6, 30)},
    {"id": "O004", "account_id": "A003", "owner_id": "U001",
     "name": "HealthFirst - Zero Trust Member Portal", "amount": 890_000,
     "probability": 80, "stage": "Proposal/Price Quote", "close_date": date(2026, 7, 15)},
    {"id": "O005", "account_id": "A002", "owner_id": "U005",
     "name": "CareConnect - Clinical Network Refresh", "amount": 580_000,
     "probability": 60, "stage": "Needs Analysis", "close_date": date(2026, 9, 30)},
    {"id": "O006", "account_id": "A004", "owner_id": "U006",
     "name": "Midwest Medical Devices - K8s IoT Platform", "amount": 720_000,
     "probability": 50, "stage": "Value Proposition", "close_date": date(2026, 11, 15)},
    # Indianapolis
    {"id": "O007", "account_id": "A005", "owner_id": "U004",
     "name": "Midwest Pharma - Genomics Data Storage Tier", "amount": 1_800_000,
     "probability": 70, "stage": "Proposal/Price Quote", "close_date": date(2026, 8, 15)},
    {"id": "O008", "account_id": "A005", "owner_id": "U004",
     "name": "Midwest Pharma - Clinical Trial Data Archive", "amount": 640_000,
     "probability": 75, "stage": "Negotiation/Review", "close_date": date(2026, 7, 31)},
    {"id": "O009", "account_id": "A006", "owner_id": "U003",
     "name": "Crossroads Health - Cloud-Native EHR Platform", "amount": 2_400_000,
     "probability": 45, "stage": "Qualification", "close_date": date(2026, 12, 31)},
    # Detroit / Michigan
    {"id": "O010", "account_id": "A007", "owner_id": "U002",
     "name": "Precision Medical - AI Diagnostics Platform", "amount": 1_100_000,
     "probability": 55, "stage": "Needs Analysis", "close_date": date(2026, 10, 31)},
    {"id": "O011", "account_id": "A008", "owner_id": "U004",
     "name": "Great Lakes Imaging - PACS Storage Platform", "amount": 960_000,
     "probability": 70, "stage": "Proposal/Price Quote", "close_date": date(2026, 8, 31)},
    # Cleveland / Ohio
    {"id": "O012", "account_id": "A009", "owner_id": "U001",
     "name": "Great Lakes Children's - Zero Trust Security", "amount": 1_400_000,
     "probability": 80, "stage": "Negotiation/Review", "close_date": date(2026, 6, 15)},
    {"id": "O013", "account_id": "A010", "owner_id": "U006",
     "name": "OhioHealth - K8s Healthcare Platform", "amount": 2_800_000,
     "probability": 40, "stage": "Qualification", "close_date": date(2026, 12, 31)},
    # Milwaukee
    {"id": "O014", "account_id": "A011", "owner_id": "U002",
     "name": "BioGenesis - ML Drug Discovery Pipeline", "amount": 950_000,
     "probability": 60, "stage": "Value Proposition", "close_date": date(2026, 9, 30)},
    {"id": "O015", "account_id": "A012", "owner_id": "U005",
     "name": "Northshore Surgical - OR Network Upgrade", "amount": 430_000,
     "probability": 65, "stage": "Proposal/Price Quote", "close_date": date(2026, 8, 31)},
    # Minneapolis
    {"id": "O016", "account_id": "A013", "owner_id": "U002",
     "name": "North Star Medical - AI Nursing Assistant", "amount": 2_100_000,
     "probability": 70, "stage": "Proposal/Price Quote", "close_date": date(2026, 8, 15)},
    {"id": "O017", "account_id": "A013", "owner_id": "U006",
     "name": "North Star Medical - K8s Care Coordination Platform", "amount": 1_600_000,
     "probability": 60, "stage": "Value Proposition", "close_date": date(2026, 9, 30)},
    {"id": "O018", "account_id": "A014", "owner_id": "U004",
     "name": "Twin Cities Pharma - Research Data Warehouse", "amount": 780_000,
     "probability": 50, "stage": "Needs Analysis", "close_date": date(2026, 11, 30)},
    # St. Louis
    {"id": "O019", "account_id": "A015", "owner_id": "U003",
     "name": "Gateway Health - Hybrid Cloud Strategy", "amount": 1_950_000,
     "probability": 35, "stage": "Prospecting", "close_date": date(2027, 1, 31)},
    # Pittsburgh
    {"id": "O020", "account_id": "A016", "owner_id": "U002",
     "name": "Steel City Medical - Surgical AI Platform", "amount": 2_500_000,
     "probability": 65, "stage": "Proposal/Price Quote", "close_date": date(2026, 8, 31)},
    {"id": "O021", "account_id": "A016", "owner_id": "U003",
     "name": "Steel City Medical - Cloud Infrastructure Overhaul", "amount": 1_200_000,
     "probability": 55, "stage": "Needs Analysis", "close_date": date(2026, 10, 31)},
    {"id": "O022", "account_id": "A006", "owner_id": "U006",
     "name": "Crossroads Health - Container Platform Pilot", "amount": 380_000,
     "probability": 55, "stage": "Needs Analysis", "close_date": date(2026, 10, 15)},
    {"id": "O023", "account_id": "A010", "owner_id": "U003",
     "name": "OhioHealth - Cloud DR Solution", "amount": 720_000,
     "probability": 45, "stage": "Qualification", "close_date": date(2026, 11, 30)},
    {"id": "O024", "account_id": "A015", "owner_id": "U005",
     "name": "Gateway Health - Network Modernization", "amount": 640_000,
     "probability": 30, "stage": "Prospecting", "close_date": date(2027, 2, 28)},
]

CONFERENCES = [
    {"id": "CF001", "name": "HIMSS 2026", "city": "Las Vegas", "state": "NV",
     "start_date": date(2026, 3, 9), "end_date": date(2026, 3, 13), "ebx_slots": 10,
     "description": "Healthcare Information and Management Systems Society annual conference"},
    {"id": "CF002", "name": "Health 2.0 Chicago 2026", "city": "Chicago", "state": "IL",
     "start_date": date(2026, 9, 10), "end_date": date(2026, 9, 12), "ebx_slots": 6,
     "description": "Digital health innovation and technology"},
    {"id": "CF003", "name": "Bio-IT World 2026", "city": "Boston", "state": "MA",
     "start_date": date(2026, 5, 12), "end_date": date(2026, 5, 15), "ebx_slots": 8,
     "description": "Life sciences and pharma IT conference"},
]

ATTENDEES = [
    # HIMSS - Las Vegas
    {"conf_id": "CF001", "user_id": "U001", "role": "Sales Lead",
     "hotel": "The Venetian Resort", "hotel_addr": "3355 Las Vegas Blvd S, Las Vegas, NV 89109",
     "check_in": date(2026, 3, 8), "check_out": date(2026, 3, 14),
     "flight_in": "AA 231 · Mar 8 · LAS arrives 1:00 PM",
     "flight_out": "AA 234 · Mar 14 · Departs LAS 4:00 PM"},
    {"conf_id": "CF001", "user_id": "U002", "role": "AI/ML Healthcare Lead",
     "hotel": "MGM Grand Las Vegas", "hotel_addr": "3799 Las Vegas Blvd S, Las Vegas, NV 89109",
     "check_in": date(2026, 3, 9), "check_out": date(2026, 3, 13),
     "flight_in": "DL 511 · Mar 9 · LAS arrives 10:00 AM",
     "flight_out": "DL 514 · Mar 13 · Departs LAS 7:00 PM"},
    {"conf_id": "CF001", "user_id": "U004", "role": "Medical Storage Specialist",
     "hotel": "MGM Grand Las Vegas", "hotel_addr": "3799 Las Vegas Blvd S, Las Vegas, NV 89109",
     "check_in": date(2026, 3, 9), "check_out": date(2026, 3, 13),
     "flight_in": "UA 712 · Mar 9 · LAS arrives 11:30 AM",
     "flight_out": "UA 715 · Mar 13 · Departs LAS 6:00 PM"},
    # Health 2.0 Chicago
    {"conf_id": "CF002", "user_id": "U001", "role": "Sales Lead",
     "hotel": "Marriott Chicago Magnificent Mile", "hotel_addr": "540 N Michigan Ave, Chicago, IL 60611",
     "check_in": date(2026, 9, 9), "check_out": date(2026, 9, 13),
     "flight_in": "UA 334 · Sep 9 · ORD arrives 2:00 PM",
     "flight_out": "UA 337 · Sep 13 · Departs ORD 5:00 PM"},
    {"conf_id": "CF002", "user_id": "U002", "role": "AI Solutions Lead",
     "hotel": "Hyatt Regency Chicago", "hotel_addr": "151 E Wacker Dr, Chicago, IL 60601",
     "check_in": date(2026, 9, 10), "check_out": date(2026, 9, 12),
     "flight_in": "AA 881 · Sep 10 · ORD arrives 9:00 AM",
     "flight_out": "AA 884 · Sep 12 · Departs ORD 8:00 PM"},
    {"conf_id": "CF002", "user_id": "U005", "role": "Clinical Networking Lead",
     "hotel": "Hyatt Regency Chicago", "hotel_addr": "151 E Wacker Dr, Chicago, IL 60601",
     "check_in": date(2026, 9, 10), "check_out": date(2026, 9, 12),
     "flight_in": "DL 622 · Sep 10 · ORD arrives 10:30 AM",
     "flight_out": "DL 625 · Sep 12 · Departs ORD 7:00 PM"},
    # Bio-IT World - Boston
    {"conf_id": "CF003", "user_id": "U001", "role": "Sales Lead",
     "hotel": "Marriott Copley Place", "hotel_addr": "110 Huntington Ave, Boston, MA 02116",
     "check_in": date(2026, 5, 11), "check_out": date(2026, 5, 16),
     "flight_in": "DL 101 · May 11 · BOS arrives 3:00 PM",
     "flight_out": "DL 104 · May 16 · Departs BOS 5:00 PM"},
    {"conf_id": "CF003", "user_id": "U002", "role": "Pharma AI Lead",
     "hotel": "Marriott Copley Place", "hotel_addr": "110 Huntington Ave, Boston, MA 02116",
     "check_in": date(2026, 5, 12), "check_out": date(2026, 5, 15),
     "flight_in": "AA 441 · May 12 · BOS arrives 10:00 AM",
     "flight_out": "AA 444 · May 15 · Departs BOS 7:00 PM"},
]
