apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: opforcements
type: Opaque
stringData:
  POSTGRES_DB: ebxdb
  POSTGRES_USER: ebxuser
  POSTGRES_PASSWORD: ebxpass
  DATABASE_URL: postgresql://ebxuser:ebxpass@postgres-service:5432/ebxdb
