apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: opforcements-apex
type: Opaque
stringData:
  POSTGRES_DB: opforcements
  POSTGRES_USER: opf
  POSTGRES_PASSWORD: "opf-apex-db-2024"
