apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: opforcements-novatech
type: Opaque
stringData:
  DATABASE_URL: "postgresql://opf:opf-novatech-db-2024@postgres:5432/opforcements"
  JWT_SECRET: "novatech-jwt-secret-change-in-prod-2024"
