apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: opforcements-admin
type: Opaque
stringData:
  DATABASE_URL: "postgresql://opf:opf-admin-db-2024@postgres:5432/opforcements"
  JWT_SECRET: "admin-jwt-secret-change-in-prod-2024"
